### ISSUE TITLE
iOS Transaction Handling Epic

### ISSUE THREAD

**Issue by braddmiller** [zcash/ZcashLightClientKit#12]
As a mobile wallet developer I need an Android library that handles various types of zcash transactions so that I can easily integrate zcash into my wallet and interact with a majority of the existing zcash ecosystem.

Criteria:
- [x] Create, send, and receive Sapling z-address to Sapling z-address
- - [x] Construct transaction to send (success/fail indication)
- - [x] Submit transaction to server (success/fail indication)
- - [x] Confirmation that the tx was included in a block
- [ ] Receive to a t-address
- [ ] Send from a t-address to a Sapling z-address
- [x] Send from a Sapling z-address to a t-address
- [x] The state of transactions is clearly surfaced for developers

For all of the above:
1) The developer can create the transaction by passing the recipient address and amount
2) The transaction can be broadcast to the zcash network
3) Documentation on how to create and broadcast the transaction exists

**Comment by braddmiller** [comment]
Rephrasing t-address components into a standalone epic
