### ISSUE TITLE
iOS Wallet and State Management Epic

### ISSUE THREAD

**Issue by braddmiller** [zcash/ZcashLightClientKit#14]
As a mobile wallet developer I would like an SDK that provides me with all of the tools necessary to observe blockchain state and my wallet reliably so that I can easily integrate zcash shielded support into my wallet.

Criteria:
- [x] The SDK can download and decrypt blocks in order to find transactions that pertain to the wallet
- [x] The SDK must be able to recognize, acknowledge, and rectify the effects of a blockchain reorganization
- [x] Able to query for all transactions related to the wallet
- [x] Able to query for the current wallet balance
- [x] Able to query for the current block height
- [x] Able to generate Sapling keys from a ZIP32 seed
- [ ] Able to generate transparent keys from seed
- [x] Able to generate ZIP32 seed from BIP39 style mnemonic
- [x] Able to generate addresses from their associated keys
- [x] Able to initialize accounts (#15)

**Comment by braddmiller** [comment]
Not quite done, being rephrased as a deliverable epic for Q2
